CREATE TABLE issues(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_id VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  CONSTRAINT `idx_url` UNIQUE(`url`)
);